import type { Product } from "@/lib/product";

/** Studio fallback until a Storefront token is set. Mix of categories. */
export const fallbackProducts: Product[] = [
  {
    id: "navy-shawl",
    handle: "navy-shawl-cardigan",
    title: "Navy cardigan með sjal-kraga",
    subtitle: "Þungt prjón · Regular fit",
    href: "/verslun",
    image: "/images/studio/navy-shawl.jpg",
    imageAlt: "Navy cardigan",
    price: "24.990 kr.",
    badge: "NÝTT",
    colors: [
      { name: "Navy", hex: "#1e3a5f" },
      { name: "Charcoal", hex: "#3d3d3d" },
    ],
  },
  {
    id: "olive-zip",
    handle: "olive-quarter-zip",
    title: "Olive quarter-zip peysa",
    subtitle: "Prjónapeysa með rennilás",
    href: "/verslun",
    image: "/images/studio/olive-zip.jpg",
    imageAlt: "Olive zip peysa",
    price: "19.990 kr.",
    colors: [
      { name: "Olive", hex: "#5c5a3a" },
      { name: "Navy", hex: "#1e3a5f" },
      { name: "Brown", hex: "#5c3d2e" },
    ],
  },
  {
    id: "taupe-cardigan",
    handle: "taupe-zip-cardigan",
    title: "Taupe zip cardigan",
    subtitle: "Cable-knit · Klassískt snið",
    href: "/verslun",
    image: "/images/studio/taupe-cardigan.jpg",
    imageAlt: "Taupe cardigan",
    price: "22.990 kr.",
    badge: "NÝTT",
    colors: [
      { name: "Taupe", hex: "#8a7a6b" },
      { name: "Navy", hex: "#1e3a5f" },
    ],
  },
  {
    id: "black-polo",
    handle: "black-knit-polo",
    title: "Svart prjóna-polo",
    subtitle: "Rifjað prjón · Hreint snið",
    href: "/verslun",
    image: "/images/studio/black-polo.jpg",
    imageAlt: "Svart polo",
    price: "14.990 kr.",
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Grey", hex: "#6b6b6b" },
      { name: "Navy", hex: "#1e3a5f" },
    ],
  },
  {
    id: "charcoal-polo",
    handle: "charcoal-polo",
    title: "Charcoal polo",
    subtitle: "Prjón · Regular fit",
    href: "/verslun",
    image: "/images/studio/charcoal-polo.jpg",
    imageAlt: "Charcoal polo",
    price: "14.990 kr.",
    colors: [
      { name: "Charcoal", hex: "#3d3d3d" },
      { name: "Black", hex: "#1a1a1a" },
    ],
  },
  {
    id: "brown-zip",
    handle: "brown-quarter-zip",
    title: "Brún prjónapeysa",
    subtitle: "Quarter-zip · Cable-knit",
    href: "/verslun",
    image: "/images/studio/brown-zip.jpg",
    imageAlt: "Brún peysa",
    price: "19.990 kr.",
    colors: [
      { name: "Brown", hex: "#5c3d2e" },
      { name: "Olive", hex: "#5c5a3a" },
    ],
  },
  {
    id: "navy-crew",
    handle: "navy-crewneck",
    title: "Navy crewneck",
    subtitle: "Klassísk peysa án kraga",
    href: "/verslun",
    image: "/images/studio/navy-crew.jpg",
    imageAlt: "Navy crewneck",
    price: "16.990 kr.",
    colors: [
      { name: "Navy", hex: "#1e3a5f" },
      { name: "Grey", hex: "#6b6b6b" },
    ],
  },
  {
    id: "grey-polo",
    handle: "grey-knit-polo",
    title: "Grátt prjóna-polo",
    subtitle: "Rifjað prjón",
    href: "/verslun",
    image: "/images/studio/grey-polo.jpg",
    imageAlt: "Grátt polo",
    price: "14.990 kr.",
    badge: "NÝTT",
    colors: [
      { name: "Grey", hex: "#8a8a8a" },
      { name: "Black", hex: "#1a1a1a" },
      { name: "Navy", hex: "#1e3a5f" },
    ],
  },
  {
    id: "dark-polo",
    handle: "dark-knit-polo",
    title: "Dökkt polo",
    subtitle: "Prjón · Tímalaus grunnvara",
    href: "/verslun",
    image: "/images/studio/dark-polo.jpg",
    imageAlt: "Dökkt polo",
    price: "14.990 kr.",
    colors: [
      { name: "Forest", hex: "#043034" },
      { name: "Navy", hex: "#1e3a5f" },
    ],
  },
  {
    id: "navy-logo",
    handle: "navy-tj-peysa",
    title: "Navy peysa með TJ merki",
    subtitle: "Merkið saumað á brjóstið",
    href: "/verslun",
    image: "/images/studio/navy-logo.jpg",
    imageAlt: "Navy peysa með merki",
    price: "18.990 kr.",
    colors: [{ name: "Navy", hex: "#1e3a5f" }],
  },
  {
    id: "navy-back",
    handle: "navy-passform",
    title: "Navy prjónapeysa",
    subtitle: "Sniðið sést best að aftan",
    href: "/verslun",
    image: "/images/studio/navy-back.jpg",
    imageAlt: "Bakning af navy peysu",
    price: "18.990 kr.",
    colors: [
      { name: "Navy", hex: "#1e3a5f" },
      { name: "Charcoal", hex: "#3d3d3d" },
    ],
  },
  {
    id: "brown-back",
    handle: "brown-crewneck",
    title: "Brún crewneck peysa",
    subtitle: "Þungt prjón · Regular fit",
    href: "/verslun",
    image: "/images/studio/brown-back.jpg",
    imageAlt: "Brún peysa að aftan",
    price: "16.990 kr.",
    colors: [
      { name: "Brown", hex: "#5c3d2e" },
      { name: "Taupe", hex: "#8a7a6b" },
    ],
  },
];
